use_frameworks!

platform :ios, '9.0'

target 'DoSwift_Example' do
  pod 'DoSwift', :path => '../'

  target 'DoSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
